protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            
        );
    }
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','faq','error','contact','login','page','captcha'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('cart','shipment','logout'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array(),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public $data = array();

    public function actionIndex($category_id = null) {
        $category_html_helper = Category::model()->category_html_helper();
        $this->data['categories'] = $category_html_helper;
        $this->data['page'] = 'home';
        if ($category_id === null) {
            $this->data['products'] = Product::model()->findAll(array("limit" => "2", "order" => "id DESC",));
        } else {
            $this->data['page'] = 'category';
            $category_id = (int) $category_id;
            $this->data['products'] = Product::model()->findAllByAttributes(array('category_id' => $category_id));
        }
        $this->render('index', $this->data);
    }

    public function actionFaq() {
        $faq = new Faq;
        $this->data['faq'] = $faq->findAll();
        $this->render('faq', $this->data);
    }

    public function actionCart() {

        $cart = Yii::app()->user->getState('cart');
        $cart = unserialize($cart);

        if (isset($_POST['form'])) {

            $cart[] = array($_POST['form']['product_id'] => $_POST['form']['quantity']);
        }
        $cart = serialize($cart);

        Yii::app()->user->setState('cart', $cart);

        $category_html_helper = Category::model()->category_html_helper();
        $this->data['categories'] = $category_html_helper;

        $this->data['cart_products'] = Product::model()->session_to_items(unserialize($cart));
        $this->render('cart', $this->data);
    }

    public function actionShipment() {
        $cart = Yii::app()->user->getState('cart');
        if (isset($_POST['Shipment_form'])) {

            if ($_POST['Shipment_form']['action'] == 'cancel') {
                Yii::app()->user->setState('cart', NULL);
                $this->redirect(Yii::app()->homeUrl . 'site/cart/');
            }
            $category_html_helper = Category::model()->category_html_helper();
            $this->data['categories'] = $category_html_helper;
            if ($_POST['Shipment_form']['action'] == 'ship') {
                $cart = Yii::app()->user->getState('cart');
                $cart = unserialize($cart);
                $this->data['cart_products'] = Product::model()->session_to_items($cart);
                $site_setting = $this->setting();
                if ($this->data['cart_products']['info']['total_items'] < $site_setting['min_shipment_items']) {
                    Yii::app()->user->setFlash('error', "Minimum items in your cart below " . $site_setting['min_shipment_items']);
                } else {

                    $i = 0;


                    $transaction = Yii::app()->db->beginTransaction();
                    try {
                        $shipment = new Shipment;
                        $shipment_data['products'] = serialize($cart);
                        $user = User::model()->findByAttributes(array('username' => Yii::app()->user->id) ); 
                        $shipment_data['user_id'] = $user->id;
                        $shipment_data['price'] = $this->data['cart_products']['info']['total_price'];
                        $shipment_data['order_time'] = date('Y-m-d H:i:s');
                        $shipment_data['status'] = '1';
                        $shipment_data['address'] = 'test';
                        $shipment_data['user_note'] = 'test';
                        //print_r($shipment_data);die;
                        $shipment->attributes = $shipment_data;
                        $shipment->save();
                        foreach ($cart AS $item) {
                            $data1[$i]['product_id'] = key($item);
                            $data1[$i]['qantity'] = $item[$data1[$i]['product_id']];
                            $product = Product::model()->findByPk($data1[$i]['product_id']);
                            $qantity = $product->qantity - $data1[$i]['qantity'];
                            Product::model()->updateByPk($data1[$i]['product_id'], array('qantity' => $qantity));
                            $i++;
                        }

                        $transaction->commit();
                        Yii::app()->user->setState('cart', NULL);
                        Yii::app()->user->setFlash('success', "We got your order and will contact you soon");
                        $this->redirect(Yii::app()->homeUrl);
                    } catch (Exception $e) {
                        $transaction->rollBack();
                        Yii::app()->user->setFlash('error', "{$e->getMessage()}");
                        $this->refresh();
                    }
                }
            }
        }

        $this->redirect(Yii::app()->homeUrl);
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the contact page
     */
    public function actionContact() {
        $model = new ContactForm;
        if (isset($_POST['ContactForm'])) {
            $model->attributes = $_POST['ContactForm'];
            if ($model->validate()) {
                $name = '=?UTF-8?B?' . base64_encode($model->name) . '?=';
                $subject = '=?UTF-8?B?' . base64_encode($model->subject) . '?=';
                $headers = "From: $name <{$model->email}>\r\n" .
                        "Reply-To: {$model->email}\r\n" .
                        "MIME-Version: 1.0\r\n" .
                        "Content-Type: text/plain; charset=UTF-8";

                mail(Yii::app()->params['adminEmail'], $subject, $model->body, $headers);
                Yii::app()->user->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact', array('model' => $model));
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(Yii::app()->user->returnUrl);
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php
 /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode($this->pageTitle); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index'), 'visible'=>Yii::app()->user->name != "admin"),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about'), 'visible'=>Yii::app()->user->name != "admin"),
				array('label'=>'Contact', 'url'=>array('/site/contact'), 'visible'=>Yii::app()->user->name != "admin"),
				array('label'=>'FAQ', 'url'=>array('/site/faq'), 'visible'=>Yii::app()->user->name != "admin"),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Manage Users', 'url'=>array('/admin/user'), 'visible'=>Yii::app()->user->name === "admin"),
				array('label'=>'Manage Categories', 'url'=>array('/admin/category'), 'visible'=>Yii::app()->user->name === "admin"),
				array('label'=>'Manage Products', 'url'=>array('/admin/product'), 'visible'=>Yii::app()->user->name === "admin"),
				array('label'=>'Manage shipments', 'url'=>array('/admin/shipment'), 'visible'=>Yii::app()->user->name === "admin"),
				array('label'=>'Manage FAQ', 'url'=>array('/admin/faq'), 'visible'=>Yii::app()->user->name === "admin"),
				array('label'=>'site setting', 'url'=>array('/admin/setting'), 'visible'=>Yii::app()->user->name === "admin"),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>
<?php
    foreach(Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
    }
?>
	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> <br/>
		All Rights Reserved.<br/>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>